NS.Web/Controllers/CartController.cs
using AutoMapper;
using NS.Business.Cart;
using NS.Web.Models.Cart;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace NS.Web.Controllers
{
    public class CartController : Controller
    {
        private readonly ICartOperations _cartOperations;
        public CartController(ICartOperations cartOperations)
        {
            _cartOperations = cartOperations;
        }

        public ActionResult Index()
        {
            var cartItems = _cartOperations.GetAllCart();

            var cartItemViewModels = new List<CartItemViewModel>();

            if (cartItems != null && cartItems.Any())
            {
                cartItemViewModels = cartItems.Select(x => Mapper.Map<CartItemViewModel>(x)).ToList();
            }

            return View(cartItemViewModels);
        }

        public ActionResult TotalItemCount()
        {
            var cartTotalItemCountViewModel = new CartTotalItemCountViewModel();

            cartTotalItemCountViewModel.TotalItemCount = _cartOperations.TotalItemCount();

            return PartialView(cartTotalItemCountViewModel);
        }

        public ActionResult DeleteFromCart(int? productId)
        {
            if (!productId.HasValue)
                return RedirectToAction("Index");

            var currentCart = _cartOperations.GetAllCart();

            var cartItem = currentCart.FirstOrDefault(x => x.ProductId == productId);

            if (cartItem != null)
            {
                _cartOperations.RemoveFromCart(cartItem);
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateCartItem(CartItemViewModel cartItemViewModel)
        {
            if (!ModelState.IsValid)
                return RedirectToAction("Index");

            var currentCart = _cartOperations.GetAllCart();

            var cartItem = currentCart.FirstOrDefault(x => x.ProductId == cartItemViewModel.ProductId);

            if (cartItem != null)
            {
                cartItem.Quantity = cartItemViewModel.Quantity;

                _cartOperations.UpdateItemQuantityInCart(cartItem);
            }

            return RedirectToAction("Index");
        }
    }
}

NS.Web/Controllers/CategoriesController.cs
using AutoMapper;
using NS.Business.Categories;
using NS.Web.Models.Categories;
using System.Linq;
using System.Web.Mvc;

namespace NS.Web.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ICategoryRepository _categoryRepository;
        public CategoriesController(ICategoryRepository categoryRepository)
        {
            _categoryRepository = categoryRepository;
        }

        public ActionResult Navigation()
        {
            var categories = _categoryRepository
                                .List()
                                .Select(x => Mapper.Map<CategoryViewModel>(x))
                                .ToList();


            return PartialView(categories);
        }
    }
}

NS.Web/Controllers/LayoutController.cs
using System.Web.Mvc;

namespace NS.Web.Controllers
{
    public class LayoutController : Controller
    {
        public ActionResult RegistrationHeaderTop()
        {
            return PartialView();
        }

        public ActionResult TopNavigationBar()
        {
            return PartialView();
        }

        public ActionResult Footer()
        {
            return PartialView();
        }

        public ActionResult Copyright()
        {
            return PartialView();
        }
    }
}

NS.Web/Views/Layout/Copyright.cshtml
<div id="copyright">
    <div class="container">
        <div class="col-md-6">
            <p class="pull-left">© 2017 Northwind Store</p>

        </div>
        <div class="col-md-6">
            <p class="pull-right">
                Powered By <a href="https://NorthwindStore.com">NorthwindStore.com</a>
            </p>
        </div>
    </div>
</div>

NS.Web/Views/Layout/Footer.cshtml
<div id="footer" data-animate="fadeInUp">
    <div class="container">
        <div class="row">
            <div class="col-md-3 col-sm-6">
                <h4>Pages</h4>

                <ul>
                    <li>
                        <a href="text.html">About us</a>
                    </li>
                    <li>
                        <a href="text.html">Terms and conditions</a>
                    </li>
                    <li>
                        <a href="faq.html">FAQ</a>
                    </li>
                    <li>
                        <a href="contact.html">Contact us</a>
                    </li>
                </ul>

                <hr>

                <h4>User section</h4>

                <ul>
                    <li>
                        <a href="#" data-toggle="modal" data-target="#login-modal">Login</a>
                    </li>
                    <li>
                        <a href="register.html">Regiter</a>
                    </li>
                </ul>

                <hr class="hidden-md hidden-lg hidden-sm">

            </div>
            <!-- /.col-md-3 -->

            <div class="col-md-3 col-sm-6">

                <h4>Top categories</h4>

                <h5>Men</h5>

                <ul>
                    <li>
                        <a href="category.html">T-shirts</a>
                    </li>
                    <li>
                        <a href="category.html">Shirts</a>
                    </li>
                    <li>
                        <a href="category.html">Accessories</a>
                    </li>
                </ul>

                <h5>Ladies</h5>
                <ul>
                    <li>
                        <a href="category.html">T-shirts</a>
                    </li>
                    <li>
                        <a href="category.html">Skirts</a>
                    </li>
                    <li>
                        <a href="category.html">Pants</a>
                    </li>
                    <li>
                        <a href="category.html">Accessories</a>
                    </li>
                </ul>

                <hr class="hidden-md hidden-lg">

            </div>
            <!-- /.col-md-3 -->

            <div class="col-md-3 col-sm-6">

                <h4>Where to find us</h4>

                <p>
                    <strong>Obaju Ltd.</strong>
                    <br>13/25 New Avenue
                    <br>New Heaven
                    <br>45Y 73J
                    <br>England
                    <br>
                    <strong>Great Britain</strong>
                </p>

                <a href="contact.html">Go to contact page</a>

                <hr class="hidden-md hidden-lg">

            </div>
            <!-- /.col-md-3 -->



            <div class="col-md-3 col-sm-6">

                <h4>Get the news</h4>

                <p class="text-muted">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>

                <form>
                    <div class="input-group">

                        <input type="text" class="form-control">

                        <span class="input-group-btn">

                            <button class="btn btn-default" type="button">Subscribe!</button>

                        </span>

                    </div>
                    <!-- /input-group -->
                </form>

                <hr>

                <h4>Stay in touch</h4>

                <p class="social">
                    <a href="#" class="facebook external" data-animate-hover="shake"><i class="fa fa-facebook"></i></a>
                    <a href="#" class="twitter external" data-animate-hover="shake"><i class="fa fa-twitter"></i></a>
                    <a href="#" class="instagram external" data-animate-hover="shake"><i class="fa fa-instagram"></i></a>
                    <a href="#" class="gplus external" data-animate-hover="shake"><i class="fa fa-google-plus"></i></a>
                    <a href="#" class="email external" data-animate-hover="shake"><i class="fa fa-envelope"></i></a>
                </p>


            </div>
            <!-- /.col-md-3 -->

        </div>
        <!-- /.row -->

    </div>
    <!-- /.container -->
</div>

NS.Web/Views/Layout/RegistrationHeaderTop.cshtml
<div id="top">
    <div class="container">
        <div class="col-md-6 offer" data-animate="fadeInDown">

        </div>
        <div class="col-md-6" data-animate="fadeInDown">
            <ul class="menu">
                <li>
                    <a href="#" data-toggle="modal" data-target="#login-modal">Login</a>
                </li>
                <li>
                    <a href="register.html">Register</a>
                </li>
                <li>
                    <a href="contact.html">Contact</a>
                </li>
            </ul>
        </div>
    </div>

    <div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="Login" aria-hidden="true">
        <div class="modal-dialog modal-sm">

            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="Login">Customer login</h4>
                </div>
                <div class="modal-body">
                    <form action="customer-orders.html" method="post">
                        <div class="form-group">
                            <input type="text" class="form-control" id="email-modal" placeholder="email">
                        </div>
                        <div class="form-group">
                            <input type="password" class="form-control" id="password-modal" placeholder="password">
                        </div>

                        <p class="text-center">
                            <button class="btn btn-primary"><i class="fa fa-sign-in"></i> Log in</button>
                        </p>

                    </form>

                    <p class="text-center text-muted">Not registered yet?</p>
                    <p class="text-center text-muted"><a href="register.html"><strong>Register now</strong></a>! It is easy and done in 1&nbsp;minute and gives you access to special discounts and much more!</p>

                </div>
            </div>
        </div>
    </div>
</div>

NS.Web/Views/Layout/TopNavigationBar.cshtml
<div class="navbar navbar-default yamm" role="navigation" id="navbar">
    <div class="container">
        <div class="navbar-header">

            <a class="navbar-brand home" href="index.html" data-animate-hover="bounce">
                <img src="@Url.Content("~/Content/img/logo.png")" alt="Northwind" class="hidden-xs">
                <img src="@Url.Content("~/Content/img/logo-small.png")" alt="Northwind" class="visible-xs"><span class="sr-only">Northwind - go to homepage</span>
            </a>
            <div class="navbar-buttons">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation">
                    <span class="sr-only">Toggle navigation</span>
                    <i class="fa fa-align-justify"></i>
                </button>
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#search">
                    <span class="sr-only">Toggle search</span>
                    <i class="fa fa-search"></i>
                </button>
                <a class="btn btn-default navbar-toggle" href="@Url.Action("Index","Cart")">
                   @Html.Action("TotalItemCount", "Cart")
                </a>
            </div>
        </div>
        <!--/.navbar-header -->
        <div class="navbar-collapse collapse" id="navigation">

            <ul class="nav navbar-nav navbar-left">
                <li class="active">
                    <a href="/">Home</a>
                </li>
                <li class="dropdown yamm-fw">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="200">Products <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <div class="yamm-content">
                                <div class="row">
                                    @Html.Action("Navigation", "Categories")
                                </div>
                            </div>
                            <!-- /.yamm-content -->
                        </li>
                    </ul>
                </li>
            </ul>

        </div>
        <!--/.nav-collapse -->

        <div class="navbar-buttons">

            <div class="navbar-collapse collapse right" id="basket-overview">
                <a href="@Url.Action("Index","Cart")" class="btn btn-primary navbar-btn">
                    @Html.Action("TotalItemCount", "Cart")
                </a>
            </div>
            <!--/.nav-collapse -->

            <div class="navbar-collapse collapse right" id="search-not-mobile">
                <button type="button" class="btn navbar-btn btn-primary" data-toggle="collapse" data-target="#search">
                    <span class="sr-only">Toggle search</span>
                    <i class="fa fa-search"></i>
                </button>
            </div>

        </div>

        <div class="collapse clearfix" id="search">

            <form class="navbar-form" role="search">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search">
                    <span class="input-group-btn">

                        <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i></button>

                    </span>
                </div>
            </form>

        </div>
        <!--/.nav-collapse -->

    </div>
    <!-- /.container -->
</div>