NS.Web/Areas/Administration/Controllers/ManageCategoriesController.cs
using AutoMapper;
using NS.Business.Categories;
using NS.Orm;
using NS.Web.Areas.Administration.Models.Categories;
using System;
using System.Linq;
using System.Web.Mvc;

namespace NS.Web.Areas.Administration.Controllers
{
    public class ManageCategoriesController : Controller
    {
        private readonly ICategoryRepository _categoryRepository;
        public ManageCategoriesController(ICategoryRepository categoryRepository)
        {
            _categoryRepository = categoryRepository;
        }
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View(new CategoryViewModel());
        }

        [HttpPost]
        public ActionResult Create(CategoryViewModel categoryViewModel)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View(categoryViewModel);
                
                var category = Mapper.Map<Category>(categoryViewModel);

                _categoryRepository.Create(category);

                return RedirectToAction("List");
            }
            catch (Exception)
            {
                return View(categoryViewModel);
            }
        }

        public ActionResult List()
        {
            var categories = _categoryRepository.List();

            var categoryViewModels = categories.Select(x => Mapper.Map<CategoryViewModel>(x)).ToList();

            return View(categoryViewModels);
        }

        public ActionResult Delete(int? id)
        {
            try
            {
                if (!id.HasValue)
                    return RedirectToAction("List");

                _categoryRepository.Delete(id.Value);

                return RedirectToAction("List");
            }
            catch (Exception exception)
            {
                return RedirectToAction("List");
            }
        }

        public ActionResult Detail(int? id)
        {
            if (!id.HasValue)
                return RedirectToAction("List");

            var category = _categoryRepository.Load(id.Value);

            var categoryViewModel = Mapper.Map<CategoryViewModel>(category);

            return View(categoryViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Detail(CategoryViewModel categoryViewModel)
        {
            if (!ModelState.IsValid)
                return View(categoryViewModel);
            
            var category = Mapper.Map<Category>(categoryViewModel);

            _categoryRepository.Update(category);

            return RedirectToAction("List");
        }
    }
}

NS.Web/Areas/Administration/Controllers/ManageProductsController.cs
using System.Web.Mvc;

namespace NS.Web.Areas.Administration.Controllers
{
    public class ManageProductsController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List()
        {
            return new EmptyResult();
        }
    }
}

NS.Web/Areas/Administration/Controllers/ManageSuppliersController.cs
using System.Web.Mvc;

namespace NS.Web.Areas.Administration.Controllers
{
    public class ManageSuppliersController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List()
        {
            return new EmptyResult();
        }
    }
}

NS.Web/Controllers/LayoutController.cs
using System.Web.Mvc;

namespace NS.Web.Controllers
{
    public class LayoutController : Controller
    {
        public ActionResult RegistrationHeaderTop()
        {
            return PartialView();
        }

        public ActionResult TopNavigationBar()
        {
            return PartialView();
        }

        public ActionResult Footer()
        {
            return PartialView();
        }

        public ActionResult Copyright()
        {
            return PartialView();
        }
    }
}

NS.Web/Areas/Administration/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Northwind Backoffice</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Northwind Backoffice", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Kategoriler","List", "ManageCategories")</li> 
                    <li>@Html.ActionLink("Tedarikçiler", "List", "ManageSuppliers")</li>
                    <li>@Html.ActionLink("Ürünler", "List", "ManageProducts")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Northwind Backoffice</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.12.4.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("InternalScripts", false)
</body>
</html>