NS.Web/Areas/Administration/Models/Dashboard/CategoriesCountViewModel.cs
namespace NS.Web.Areas.Administration.Models.Dashboard
{
    public class CategoriesCountViewModel
    {
        public int CategoriesCount { get; set; }
    }
}

NS.Web/Areas/Administration/Models/Dashboard/ProductsCountViewModel.cs
namespace NS.Web.Areas.Administration.Models.Dashboard
{
    public class ProductsCountViewModel
    {
        public int ProductsCount { get; set; }
    }
}

NS.Web/Areas/Administration/Models/Dashboard/SuppliersCountViewModel.cs
namespace NS.Web.Areas.Administration.Models.Dashboard
{
    public class SuppliersCountViewModel
    {
        public int SuppliersCount { get; set; }
    }
}

NS.Web/Areas/Administration/Controllers/DashboardController.cs
using NS.Business.Categories;
using NS.Business.Products;
using NS.Business.Suppliers;
using NS.Infrastructure.Paging;
using NS.Web.Areas.Administration.Models.Dashboard;
using System.Web.Mvc;

namespace NS.Web.Areas.Administration.Controllers
{
    public class DashboardController : Controller
    {
        private readonly ICategoryRepository _categoryRepository;
        private readonly ISupplierRepository _supplierRepository;
        private readonly IProductRepository _productRepository;

        public DashboardController(ICategoryRepository categoryRepository, ISupplierRepository supplierRepository, IProductRepository productRepository)
        {
            _categoryRepository = categoryRepository;
            _supplierRepository = supplierRepository;
            _productRepository = productRepository;
        }
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CategoriesCount()
        {
            var categoriesCountViewModel = new CategoriesCountViewModel();

            categoriesCountViewModel.CategoriesCount = _categoryRepository.List().Count;

            return PartialView(categoriesCountViewModel);
        }

        public ActionResult ProductsCount()
        {
            var productsCountViewModel = new ProductsCountViewModel();

            var productSearchCriteria = new ProductSearchCriteria();
            productSearchCriteria.PagedBase = new PagedBase();
            productSearchCriteria.PagedBase.PageSize = int.MaxValue;
            productSearchCriteria.PagedBase.PageIndex = int.MaxValue;

            productsCountViewModel.ProductsCount = _productRepository.Search(productSearchCriteria).TotalItemCount;

            return PartialView(productsCountViewModel);
        }

        public ActionResult SuppliersCount()
        {
            var suppliersCountViewModel = new SuppliersCountViewModel();

            suppliersCountViewModel.SuppliersCount = _supplierRepository.List().Count;

            return PartialView(suppliersCountViewModel);
        }
    }
}

NS.Web/Areas/Administration/Views/Dashboard/CategoriesCount.cshtml
@using NS.Web.Areas.Administration.Models
@model CategoriesCountViewModel
<div class="col-md-3">
    <div class="panel panel-default">
        <div class="panel-body">Total Categories</div>
        <div class="panel-footer">@Model.CategoriesCount</div>
    </div>
</div> 

NS.Web/Areas/Administration/Views/Dashboard/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div class="row">
    @Html.Action("CategoriesCount", "Dashboard")
    @Html.Action("ProductsCount", "Dashboard")
    @Html.Action("SuppliersCount", "Dashboard")
</div>

NS.Web/Areas/Administration/Views/Dashboard/ProductsCount.cshtml
@using NS.Web.Areas.Administration.Models
@model ProductsCountViewModel
<div class="col-md-3">
    <div class="panel panel-default">
        <div class="panel-body">Total Products</div>
        <div class="panel-footer">@Model.ProductsCount</div>
    </div>
</div> 

NS.Web/Areas/Administration/Views/Dashboard/SuppliersCount.cshtml
@using NS.Web.Areas.Administration.Models
@model SuppliersCountViewModel
<div class="col-md-3">
    <div class="panel panel-default">
        <div class="panel-body">Total Suppliers</div>
        <div class="panel-footer">@Model.SuppliersCount</div>
    </div>
</div> 